name: Build

on:
  push:
    branches: [ work, master, main ]
  pull_request:
    branches: [ work, master, main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true      # stop duplicate runs on same branch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3
      - name: Build solution
        run: msbuild NegativeScreen.sln /p:Configuration=Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NegativeScreen-${{ github.ref_name }}
          path: NegativeScreen/bin/Release/
