name: Build

on:
  push:
    branches:[ work ]
  pull_request:
    branches: [ work ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3
      - name: Build solution
        run: msbuild NegativeScreen.sln /p:Configuration=Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NegativeScreen
          path: NegativeScreen/bin/Release/

