name: Build

on:
  push:
    branches: [ work, master ]
  pull_request:
    branches: [ work, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3
      - name: Build solution
        run: msbuild NegativeScreen.sln /p:Configuration=Release /p:Platform=x64
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NegativeScreen
          path: NegativeScreen/bin/x64/Release/

