name: Build

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Build x86
      run: msbuild NegativeScreen.sln /p:Configuration=Release /p:Platform=x86
    - name: Build x64
      run: msbuild NegativeScreen.sln /p:Configuration=Release /p:Platform=x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NegativeScreen-build
        path: |
          NegativeScreen/bin/Release/
          NegativeScreen/bin/x64/Release/

